#≈‰÷√∂Àø⁄¬∑æ∂
server:
  port: 8082
  servlet:
    context-path: /Jwt

#≈‰÷√spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_Jwt?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123
    driver-class-name: org.mariadb.jdbc.Driver


#log
#lOG
logging:
  level:
   com.example.jwt_demo: DEBUG
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.jwt_demo.pojo
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true